#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(Feat|Fix|Docs|Test|Style|Refactor|Build|Revert)(\(.+?\))?: .{1,}$";
then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood, first letter capitalized>: <what was done>"
  echo "Allowed verbs in imperative mood: Feat, Cut, Fix, Bump, Make, Start, Stop, Refactor, Reformat, Optimise, Document, Merge"
  echo "Example: 'Feat: Add login button'"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
